package Battleship;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import java.util.Collections;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author vansh
 */
public class PlayerUI extends javax.swing.JFrame {

	/**
	 * Creates new form PlayerUI
	 */
	public PlayerUI() {
		initComponents();
	}

	static ArrayList<Integer> count = new ArrayList<Integer>();

	public static void randomGenerator() {
		while (count.size() < 32) {
			int abc = (int) (Math.random() * ((32 - 1) + 1) + 1);
			System.out.println(abc);
			if (!count.contains(abc)) {

				switch (abc) {

				case 1:
					count.add(1);
					jButton38.doClick();
					 break;

				case 2:
					count.add(2);
					jButton39.doClick();
					 break;

				case 3:
					count.add(3);
					jButton40.doClick();
					 break;

				case 4:
					count.add(4);
					jButton41.doClick();
					 break;

				case 5:
					count.add(5);
					jButton42.doClick();
					 break;

				case 6:
					count.add(6);
					jButton43.doClick();
					 break;

				case 7:
					count.add(7);
					jButton44.doClick();
					 break;

				case 8:
					count.add(8);
					jButton45.doClick();
					 
					break;
				case 9:
					jButton46.doClick();
					count.add(9);
					break;
				case 10:
					jButton47.doClick();
					count.add(10);
					break;
				case 11:
					jButton48.doClick();
					count.add(11);
					break;
				case 12:
					jButton49.doClick();
					count.add(12);
					break;
				case 13:
					jButton50.doClick();
					count.add(13);
					break;
				case 14:
					jButton51.doClick();
					count.add(14);
					break;
				case 15:
					jButton52.doClick();
					count.add(15);
					break;
				case 16:
					jButton53.doClick();
					count.add(16);
					break;
				case 17:
					jButton54.doClick();
					count.add(17);
					break;
				case 18:
					jButton55.doClick();
					count.add(18);
					break;
				case 19:
					jButton56.doClick();
					count.add(19);
					break;
				case 20:
					jButton57.doClick();
					count.add(20);
					break;
				case 21:
					jButton58.doClick();
					count.add(21);
					break;
				case 22:
					jButton59.doClick();
					count.add(22);
					break;
				case 23:
					jButton60.doClick();
					count.add(23);
					break;
				case 24:
					jButton61.doClick();
					count.add(24);
					break;
				case 25:
					jButton62.doClick();
					count.add(25);
					break;
				case 26:
					jButton63.doClick();
					count.add(26);
					break;
				case 27:
					jButton64.doClick();
					count.add(27);
					break;
				case 28:
					jButton65.doClick();
					count.add(28);
					break;
				case 29:
					jButton66.doClick();
					count.add(29);
					break;
				case 30:
					jButton67.doClick();
					count.add(30);
					break;
				case 31:
					jButton68.doClick();
					count.add(31);
					break;
				case 32:
					jButton69.doClick();
					count.add(32);
					break;
				}
				
			}
		}
		Collections.sort(count);
		System.out.println(count);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jInternalFrame1 = new javax.swing.JInternalFrame();
		jButton69 = new javax.swing.JButton();
		jButton70 = new javax.swing.JButton();
		jButton71 = new javax.swing.JButton();
		jButton72 = new javax.swing.JButton();
		jButton73 = new javax.swing.JButton();
		jButton74 = new javax.swing.JButton();
		jButton75 = new javax.swing.JButton();
		jButton76 = new javax.swing.JButton();
		jButton77 = new javax.swing.JButton();
		jButton78 = new javax.swing.JButton();
		jButton79 = new javax.swing.JButton();
		jButton80 = new javax.swing.JButton();
		jButton81 = new javax.swing.JButton();
		jButton82 = new javax.swing.JButton();
		jButton83 = new javax.swing.JButton();
		jButton84 = new javax.swing.JButton();
		jButton85 = new javax.swing.JButton();
		jButton86 = new javax.swing.JButton();
		jButton87 = new javax.swing.JButton();
		jButton88 = new javax.swing.JButton();
		jButton89 = new javax.swing.JButton();
		jButton90 = new javax.swing.JButton();
		jButton91 = new javax.swing.JButton();
		jButton92 = new javax.swing.JButton();
		jButton93 = new javax.swing.JButton();
		jButton94 = new javax.swing.JButton();
		jButton95 = new javax.swing.JButton();
		jButton96 = new javax.swing.JButton();
		jButton97 = new javax.swing.JButton();
		jButton98 = new javax.swing.JButton();
		jButton99 = new javax.swing.JButton();
		jButton100 = new javax.swing.JButton();
		jInternalFrame2 = new javax.swing.JInternalFrame();
		jButton37 = new javax.swing.JButton();
		jButton38 = new javax.swing.JButton();
		jButton39 = new javax.swing.JButton();
		jButton40 = new javax.swing.JButton();
		jButton41 = new javax.swing.JButton();
		jButton42 = new javax.swing.JButton();
		jButton43 = new javax.swing.JButton();
		jButton44 = new javax.swing.JButton();
		jButton45 = new javax.swing.JButton();
		jButton46 = new javax.swing.JButton();
		jButton47 = new javax.swing.JButton();
		jButton48 = new javax.swing.JButton();
		jButton49 = new javax.swing.JButton();
		jButton50 = new javax.swing.JButton();
		jButton51 = new javax.swing.JButton();
		jButton52 = new javax.swing.JButton();
		jButton53 = new javax.swing.JButton();
		jButton54 = new javax.swing.JButton();
		jButton55 = new javax.swing.JButton();
		jButton56 = new javax.swing.JButton();
		jButton57 = new javax.swing.JButton();
		jButton58 = new javax.swing.JButton();
		jButton59 = new javax.swing.JButton();
		jButton60 = new javax.swing.JButton();
		jButton61 = new javax.swing.JButton();
		jButton62 = new javax.swing.JButton();
		jButton66 = new javax.swing.JButton();
		jButton63 = new javax.swing.JButton();
		jButton64 = new javax.swing.JButton();
		jButton65 = new javax.swing.JButton();
		jButton67 = new javax.swing.JButton();
		jButton68 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Player 1");

		jLabel2.setText("NAme1");

		jLabel3.setText("Player 2 ");

		jLabel4.setText("NAme 2");

		jPanel1.setBackground(new java.awt.Color(199, 93, 93));
		jPanel1.setLayout(null);

		jLabel5.setText("Player 1 Score");

		jLabel6.setText("Player 2 Score");

		jInternalFrame1.setVisible(true);
		jInternalFrame1.getContentPane().setLayout(new java.awt.GridLayout(8, 8));

		jButton69.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton69ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton69);

		jButton70.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton70ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton70);

		jButton71.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton71ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton71);

		jButton72.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton72ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton72);

		jButton73.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton73ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton73);

		jButton74.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton74ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton74);

		jButton75.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton75ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton75);

		jButton76.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton76ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton76);

		jButton77.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton77ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton77);

		jButton78.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton78ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton78);

		jButton79.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton79ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton79);

		jButton80.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton80ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton80);

		jButton81.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton81ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton81);

		jButton82.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton82ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton82);

		jButton83.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton83ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton83);

		jButton84.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton84ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton84);

		jButton85.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton85ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton85);

		jButton86.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton86ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton86);

		jButton87.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton87ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton87);

		jButton88.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton88ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton88);

		jButton89.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton89ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton89);

		jButton90.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton90ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton90);

		jButton91.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton91ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton91);

		jButton92.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton92ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton92);

		jButton93.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton93ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton93);

		jButton94.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton94ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton94);

		jButton95.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton95ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton95);

		jButton96.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton96ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton96);

		jButton97.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton97ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton97);

		jButton98.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton98ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton98);

		jButton99.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton99ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton99);

		jButton100.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton100ActionPerformed(evt);
			}
		});
		jInternalFrame1.getContentPane().add(jButton100);

		jInternalFrame2.setVisible(true);
		jInternalFrame2.getContentPane().setLayout(new java.awt.GridLayout(8, 8));

		jButton37.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton37ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton37);

		jButton38.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton38ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton38);

		jButton39.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton39ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton39);

		jButton40.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton40ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton40);

		jButton41.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton41ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton41);

		jButton42.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton42ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton42);

		jButton43.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton43ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton43);

		jButton44.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton44ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton44);

		jButton45.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton45ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton45);

		jButton46.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton46ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton46);

		jButton47.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton47ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton47);

		jButton48.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton48ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton48);

		jButton49.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton49ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton49);

		jButton50.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton50ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton50);

		jButton51.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton51ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton51);

		jButton52.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton52ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton52);

		jButton53.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton53ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton53);

		jButton54.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton54ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton54);

		jButton55.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton55ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton55);

		jButton56.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton56ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton56);

		jButton57.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton57ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton57);

		jButton58.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton58ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton58);

		jButton59.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton59ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton59);

		jButton60.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton60ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton60);

		jButton61.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton61ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton61);

		jButton62.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton62ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton62);

		jButton66.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton66ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton66);

		jButton63.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton63ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton63);

		jButton64.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton64ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton64);

		jButton65.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton65ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton65);

		jButton67.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton67ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton67);

		jButton68.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton68ActionPerformed(evt);
			}
		});
		jInternalFrame2.getContentPane().add(jButton68);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator2)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108,
										Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(121, 121, 121)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(
												jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(33, 33, 33))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 374,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28))))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
								.addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 374,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(405, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
						.addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 393,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(20, 20, 20))
				.addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addContainerGap(158, Short.MAX_VALUE)
												.addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE,
														393, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(21, 21, 21))));

		pack();
	}// </editor-fold>

	private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton37.setIcon(i);
		System.out.println("one is pressed");

	}

	private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton38.setIcon(i);

		// TODO add your handling code here:
	}

	private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton39.setIcon(i); // TODO add your handling code here:
	}

	private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton40.setIcon(i); // TODO add your handling code here:
	}

	private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton41.setIcon(i); // TODO add your handling code here:
	}

	private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton42.setIcon(i); // TODO add your handling code here:
	}

	private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton43.setIcon(i); // TODO add your handling code here:
	}

	private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton44.setIcon(i); // TODO add your handling code here:
	}

	private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton45.setIcon(i); // TODO add your handling code here:
	}

	private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton46.setIcon(i); // TODO add your handling code here:
	}

	private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton47.setIcon(i); // TODO add your handling code here:
	}

	private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton48.setIcon(i); // TODO add your handling code here:
	}

	private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton49.setIcon(i); // TODO add your handling code here:
	}

	private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton50.setIcon(i); // TODO add your handling code here:
	}

	private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton51.setIcon(i); // TODO add your handling code here:
	}

	private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton52.setIcon(i); // TODO add your handling code here:
	}

	private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton53.setIcon(i); // TODO add your handling code here:
	}

	private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton54.setIcon(i); // TODO add your handling code here:
	}

	private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton55.setIcon(i); // TODO add your handling code here:
	}

	private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton56.setIcon(i); // TODO add your handling code here:
	}

	private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton57.setIcon(i); // TODO add your handling code here:
	}

	private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton58.setIcon(i); // TODO add your handling code here:
	}

	private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton59.setIcon(i); // TODO add your handling code here:
	}

	private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton60.setIcon(i); // TODO add your handling code here:
	}

	private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton61.setIcon(i); // TODO add your handling code here:
	}

	private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton62.setIcon(i); // TODO add your handling code here:
	}

	private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton63.setIcon(i); // TODO add your handling code here:
	}

	private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton64.setIcon(i); // TODO add your handling code here:
	}

	private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton65.setIcon(i); // TODO add your handling code here:
	}

	private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton66.setIcon(i); // TODO add your handling code here:
	}

	private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		jButton67.setIcon(i); // TODO add your handling code here:
	}

	private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton68.setIcon(i); // TODO add your handling code here:
	}

	private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {
		Icon i = new ImageIcon(
				"C:\\Users\\vansh\\Documents\\NetBeansProjects\\JavaApplication14\\src\\javaapplication14\\image1.jpg");
		jButton69.setIcon(i); // TODO add your handling code here:
	}

	private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {
		//Icon i = new ImageIcon("C:\\Users\\vansh\\Desktop\\cross.JPG");
		//jButton70.setIcon(i); // TODO add your handling code here:
	}

	private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton85ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton89ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton91ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton92ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton93ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton94ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton96ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton97ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton98ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton99ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PlayerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PlayerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PlayerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PlayerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PlayerUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton37;
	private javax.swing.JButton jButton100;
	private static javax.swing.JButton jButton38;
	private static javax.swing.JButton jButton39;
	private static javax.swing.JButton jButton40;
	private static javax.swing.JButton jButton41;
	private static javax.swing.JButton jButton42;
	private static javax.swing.JButton jButton43;
	private static javax.swing.JButton jButton44;
	private static javax.swing.JButton jButton45;
	private static javax.swing.JButton jButton46;
	private static javax.swing.JButton jButton47;
	private static javax.swing.JButton jButton48;
	private static javax.swing.JButton jButton49;
	private static javax.swing.JButton jButton50;
	private static javax.swing.JButton jButton51;
	private static javax.swing.JButton jButton52;
	private static javax.swing.JButton jButton53;
	private static javax.swing.JButton jButton54;
	private static javax.swing.JButton jButton55;
	private static javax.swing.JButton jButton56;
	private static javax.swing.JButton jButton57;
	private static javax.swing.JButton jButton58;
	private static javax.swing.JButton jButton59;
	private static javax.swing.JButton jButton60;
	private static javax.swing.JButton jButton61;
	private static javax.swing.JButton jButton62;
	private static javax.swing.JButton jButton63;
	private static javax.swing.JButton jButton64;
	private static javax.swing.JButton jButton65;
	private static javax.swing.JButton jButton66;
	private static javax.swing.JButton jButton67;
	private static javax.swing.JButton jButton68;
	private static javax.swing.JButton jButton69;
	private javax.swing.JButton jButton70;
	private javax.swing.JButton jButton71;
	private javax.swing.JButton jButton72;
	private javax.swing.JButton jButton73;
	private javax.swing.JButton jButton74;
	private javax.swing.JButton jButton75;
	private javax.swing.JButton jButton76;
	private javax.swing.JButton jButton77;
	private javax.swing.JButton jButton78;
	private javax.swing.JButton jButton79;
	private javax.swing.JButton jButton80;
	private javax.swing.JButton jButton81;
	private javax.swing.JButton jButton82;
	private javax.swing.JButton jButton83;
	private javax.swing.JButton jButton84;
	private javax.swing.JButton jButton85;
	private javax.swing.JButton jButton86;
	private javax.swing.JButton jButton87;
	private javax.swing.JButton jButton88;
	private javax.swing.JButton jButton89;
	private javax.swing.JButton jButton90;
	private javax.swing.JButton jButton91;
	private javax.swing.JButton jButton92;
	private javax.swing.JButton jButton93;
	private javax.swing.JButton jButton94;
	private javax.swing.JButton jButton95;
	private javax.swing.JButton jButton96;
	private javax.swing.JButton jButton97;
	private javax.swing.JButton jButton98;
	private javax.swing.JButton jButton99;
	private javax.swing.JInternalFrame jInternalFrame1;
	private javax.swing.JInternalFrame jInternalFrame2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JSeparator jSeparator2;
	// End of variables declaration
}
